### ISSUE TITLE
ENOENT error when running adapt-buildkit install rub

### ISSUE THREAD

**Issue by tomgreenfield** [oliverfoster/adapt-buildkits#1]
As requested, dumping this error log here:

![i51 cimgpsh_orig](https://cloud.githubusercontent.com/assets/922987/8903995/ccd3b964-3453-11e5-8751-4883f6730efb.png)

**Comment by oliverfoster** [comment]
duplicate https://github.com/cgkineo/adapt-buildkits/issues/2
