### ISSUE TITLE
Buildkit Error on update

### ISSUE THREAD

**Issue by guywillis** [oliverfoster/adapt-buildkits#2]
When running the following command to update rub from version 0.0.48 to 0.0.49:

> adapt-buildkit install rub 

I receive the following error. There seems to be an error when uninstalling the the buildkit files and installing them again to update.

> Buildkit versions found:
>  'rub', 'gulp', 'grunt'
> 
> Installing: 
>  'rub'
> 
> Cached version out of date at v0.0.48 downloading v0.0.49
> 
> Uninstalling from current directory...
> 
> fs.js:624
>   return binding.rmdir(pathModule._makeLong(path));
>                  ^
> Error: ENOTEMPTY, directory not empty 'buildkit/node_modules/less/node_modules/request/node_modules/.bin'
>     at Object.fs.rmdirSync (fs.js:624:18)
>     at Object.pub.rm (/usr/local/lib/node_modules/adapt-buildkits/libraries/fsext.js:375:31)
>     at Object.pub.entryPoint (/usr/local/lib/node_modules/adapt-buildkits/commands/uninstall.js:28:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/adapt-buildkits/commands/install.js:165:43)
>     at Object.<anonymous> (/usr/local/lib/node_modules/adapt-buildkits/commands/install.js:215:13)
>     at null._onTimeout (/usr/local/lib/node_modules/adapt-buildkits/commands/install.js:265:15)
>     at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

**Comment by oliverfoster** [comment]
still an issue, need to update installer at some point. if you retry the installation it'll succeed, so not a blocking issue atm.
