### ISSUE TITLE
Cannot install/run adapt-buildkits on Node v6

### ISSUE THREAD

**Issue by tomgreenfield** [oliverfoster/adapt-buildkits#4]
All hell breaks loose when trying to run an `adapt-buildkit` or `rub` command using Node v6 (which is now in LTS). Please see [attached](https://github.com/cgkineo/adapt-buildkits/files/548251/npm-debug.log.txt).

**Comment by oliverfoster** [comment]
updated adapt-buildkits and adapt-buildkit-rub to work with node 6.9.1. please confirm working

**Comment by oliverfoster** [comment]
ta
